# Задание 1
    Импортируйте библиотеку Numpy и дайте ей псевдоним np.
1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
import numpy as np

In [64]:
a = np.arange(12,24,1)

In [49]:
b1 = np.copy(a).reshape(2,6)

In [62]:
b1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [51]:
b2 = np.copy(a).reshape(3,4)

In [52]:
b2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [53]:
b3 = np.copy(a).reshape(4,3)

In [54]:
b3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [55]:
b4 = np.copy(a).reshape(6,2)

In [59]:
b4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [57]:
b5 = np.copy(a).reshape(12,1)

In [60]:
b5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [69]:
c1 = np.copy(a).reshape(2,-1)

In [70]:
c1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [72]:
c2 = np.copy(a).reshape(3,-1)

In [73]:
c2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [74]:
c3 = np.copy(a).reshape(4,-1)

In [75]:
c3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [78]:
c4 = np.copy(a).reshape(-1,2)

In [79]:
c4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [80]:
c5 = np.copy(a).reshape(-1,1)

In [81]:
c5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

    4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [88]:
c5.ndim  
#формально да, назвать одномерным можно, т.к. это просто траспонирование, обычного одномерного массива
#Но технически измерения тут 2, потому обращатся к любому значению надо по 2м измерениям, как к двумерному массиву.

2

    5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [21]:
a_normal = np.random.randn(12).reshape(3,4)
a_normal_flat = a_normal.flatten()
a_normal_flat

array([-0.68120427,  0.22560049,  0.13451305,  0.61939397,  0.53579939,
       -0.00669264,  0.48038567,  1.85416815, -0.06120363, -0.05031243,
        1.56005878,  1.62408298])

    6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.В чем разница между массивами a и b?

In [36]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [37]:
b = np.arange(20,0,-2).reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [41]:
#различия "a" и "b" в количестве измерений.  Это одномерный и двемерный массивы, соотвественно.
print(a.ndim)
print(b.ndim)

1
2


    7. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [50]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [49]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [54]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [53]:
np.size(v)

10

    8. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.

In [57]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [61]:
A = a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [64]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [145]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

Какой размер имеет матрица B?

In [70]:
print(B.size)  #размер матрицы
print(B.shape) 

16
(4, 4)


    Получится ли вычислить обратную матрицу для матрицы B и почему?

In [81]:
np.linalg.det(B)  # не получился, т.к. если определитель равен 0, то обратную матрицу получить нельзя

0.0

    9. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42. Создайте одномерный массив c, составленный из последовательности 16-ти случайных целых чисел от 0 до 16 невключительно.Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [104]:
np.random.seed(42)
c = np.random.randint(0, 16,16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [143]:
C = c.reshape(4,4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [146]:
D = C + (B*10)
D

array([[  56,  143,  242,  334],
       [ 150,  507,  872, 1224],
       [ 236,  869, 1492, 2126],
       [ 330, 1230, 2127, 3024]])

In [116]:
np.linalg.det(D) #определитель

-1741608.0000000035

In [122]:
np.linalg.matrix_rank(D) #ранг матрица

4

In [120]:
D_inv = np.linalg.inv(D) #обратная матрица
D_inv

array([[ 0.135368  , -0.09412681, -0.0250975 ,  0.04079219],
       [-0.17297808,  0.16351785,  0.1740805 , -0.16946638],
       [-0.05802224,  0.09496052, -0.10651536,  0.04285695],
       [ 0.09639712, -0.12303113,  0.00685229,  0.03466452]])

    10. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы.

In [130]:
D_inv[D_inv > 0] = 1
D_inv[D_inv < 0] = 0

In [142]:
D_inv

array([[1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 1.]])

    С помощью функции numpy.where, используя матрицу D_inv в качестве маски,а матрицы B и C - в качестве источников данных,получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [148]:
B = np.where(D_inv, np.copy(B), np.copy(C))
B

array([[  5,   3,  12,  32],
       [ 10,  50,  86,   4],
       [  6,  86,   2, 212],
       [ 32,  10, 212, 302]])

 ## Задание 2
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [197]:
a = np.array([[1,2,3,3,1],
              [6,8,11,10,7]]).T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [203]:
mean_a = np.mean(a,axis=0)
mean_a

array([2. , 8.4])

 ## Задание 3
Вычислите массив a_centered, отняв от значений массива а 
средние значения соответствующих признаков, содержащиеся в массиве mean_a.
Вычисление должно производиться в одно действие.
Получившийся массив должен иметь размер 5x2.

In [211]:
a_centered = a - mean_a
a_centered

array([-2.4, -0.4,  2.6,  1.6, -1.4])

 ## Задание 4
Найдите скалярное произведение столбцов массива a_centered.
В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [214]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]
a_centered_sp


5

In [213]:
a_centered_sp / 4  #N = len(a_centered) = 5, N-1 =4

2.0

## Задание 5
Число, которое мы получили в конце задания 3 является 
ковариацией двух признаков, содержащихся в массиве а.
В задании 4 мы делили сумму произведений центрированных 
признаков на N-1, а не на N, поэтому полученная нами величина 
является несмещенной оценкой ковариации.
Подробнее узнать о ковариации можно здесь:
Ссылка
В этом задании проверьте получившееся число, вычислив
ковариацию еще одним способом - с помощью функции np.cov.
В качестве аргумента m функция np.cov должна принимать транспонированный массив a.
В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение 
ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [217]:
result_matrix = np.cov(a.T)
result_matrix

array([[1. , 2. ],
       [2. , 4.3]])

In [219]:
result = result_matrix[0,1]
result

2.0